modLoader="javafml"
loaderVersion="[35,)"
license="All rights reserved"
issueTrackerURL="https://github.com/PugsMods/Combat7/issues"
[[mods]]
modId="combat7"
version="1.2.3"
displayName="Combat7"
updateJSONURL="https://raw.githubusercontent.com/PugsMods/Combat7/master/src/main/java/com/putopug/combat7/update/update.json"
displayURL="http://www.curseforge.com/minecraft/mc-mods/combat7"
logoFile="examplemod.png"
credits="Thanks To PugzAreCute_ For Making This Mod :-)"
authors="PugzAreCute_"
description='''
A Combat Mod
'''
[[dependencies.combat7]]
    modId="forge"
    mandatory=true
    versionRange="[35,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.combat7]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4]"
    ordering="NONE"
    side="BOTH"
